/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-03-24 03:36:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("\tAuthor: \t\tSzabolcs Kovacs\r\n");
      out.write("\tStudent Number: B00063874\r\n");
      out.write("\tProject: \t\tSingle-page web application with using RESTFul web services\r\n");
      out.write("\tDescription: \tThe application is built on JQuery mobile framework which uses CURD.\r\n");
      out.write("\t\t\t\t\tThe content of the application dynamically generates its page content based on URL's content.\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Toy Store</title>\r\n");
      out.write("\t\t<meta charset='utf-8' />\r\n");
      out.write("\t\t<meta name='viewport' content='width=device-width, initial-scale=1'>\r\n");
      out.write("\t\t<script charset='utf-8' type='text/javascript' src='jqm/jquery-1.11.js'></script>\r\n");
      out.write("\t\t<script type='text/javascript' src='js/helperURL.js'></script>\r\n");
      out.write("\t\t<script type='text/javascript' src='js/helperGUI.js'></script>\r\n");
      out.write("\t\t<script type='text/javascript' src='js/helperGlobal.js'></script>\r\n");
      out.write("\t\t<script type='text/javascript' src='js/app.js'></script>\r\n");
      out.write("\t\t<link rel='stylesheet' href='css/style.css' />\r\n");
      out.write("\t\t<script src='jqm/jquery.mobile-1.4.5.min.js'></script>\r\n");
      out.write("\t\t<link rel='stylesheet' type='text/css' href='jqm/jquery.mobile-1.4.5.min.css'  />\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("<!-- First Page -->\r\n");
      out.write("\t\t<div id='firstPage' data-role='page' data-theme='a'>\r\n");
      out.write("\t\t\t<div id='firstPageHeader' data-role='header'>\r\n");
      out.write("\t\t\t\t<a href='#popupAdd' data-transition='slidedown' data-rel='popup' data-position-to='window' class='ui-btn ui-shadow ui-corner-all ui-btn-icon-left ui-icon-plus myBtn'>Add</a>\r\n");
      out.write("\t\t\t\t<h1 class='pageTitle'>Toy Story</h1>\r\n");
      out.write("\t\t\t\t<a href='#' class='ui-btn ui-icon-refresh ui-shadow ui-corner-all ui-btn-icon-left myBtn' id='pageRefresh' >Refresh</a>\r\n");
      out.write("\t\t\t\t<div data-role='popup' id='popupAdd' class='ui-content' data-theme='b' data-dismissible='false'>\r\n");
      out.write("    \t\t\t\t<form>\r\n");
      out.write("    \t\t\t\t\t<div style='padding: 10px 20px' id='popupWrapper'>\r\n");
      out.write("    \t\t\t\t\t\t<p>Add New Item</p>\r\n");
      out.write("    \t\t\t\t\t\t<a href='#' data-rel='back' class='ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-left' id='popupCloseBtn'>Close</a>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<label for='addItemName' class='ui-hidden-accessible'>Name:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='addItemName' id='addItemName' value='' placeholder='toy name' required type='text'>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<label for='addItemBrand' class='ui-hidden-accessible'>Brand:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='addItemBrand' id='addItemBrand' value='' placeholder='toy brand' required type='text'>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<label for='addItemCategory' class='ui-hidden-accessible'>Category:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='addItemCategory' id='addItemCategory' value='' placeholder='toy category' required type='text'>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<label for='addItemPrice' >Price:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='ui-grid-a'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='ui-block-a'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name='euro' pattern='[0-9]*' id='addItemPriceEuro' min='0' value='' required type='number'>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='ui-block-b'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name='cent' pattern='[0-9]*' id='addItemPriceCent' min='0' max='99' required value='' type='number'>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<label for='addItemQuantity'>Quantity:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name='addItemQuantity' id='addItemQuantity' value='1' min='0' max='100' required type='range'>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class='ui-grid-a'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='ui-block-a'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='#' class='ui-btn ui-mini ui-corner-all ui-shadow ui-btn-a ui-btn-icon-left ui-icon-delete ui-corner-all' id='addItemBtnReset'>Reset</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='ui-block-b'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='#' class='ui-btn ui-mini ui-corner-all ui-shadow ui-btn-a ui-btn-icon-left ui-icon-delete ui-corner-all' id='addItemBtnSubmit'>Add</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id='firstPageContent' data-role='content'>\r\n");
      out.write("\t\t\t\t<div id='firstPageSearchOption'>\r\n");
      out.write("\t\t\t\t\t<fieldset class='ui-grid-b'>\r\n");
      out.write("\t\t\t\t\t\t<div class='ui-block-a'>\r\n");
      out.write("\t\t\t\t\t\t\t<select class='myBtn' name='select-choice' id='searchOption' \r\n");
      out.write("\t\t\t\t\t\t\t\tdata-corners='true'\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-mini='true'\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-iconshadow='true' \r\n");
      out.write("\t\t\t\t\t\t\t\tdata-theme='a'\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-icon='arrow-r'\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-iconpos='right'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='select'>Search</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='all'>All Item</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='name'>Name</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='brand'>Brand</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='category'>Category</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='price'>Price</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='ui-block-b' id='firstPageSearchBtn'></div>\r\n");
      out.write("\t\t\t\t\t\t<div class='ui-block-c' id='firstPageSearchInput'></div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class='pageTitle'><h1>Stock Information</h1></div>\r\n");
      out.write("\t\t\t\t<div id='firstPageDisplayBox'>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div data-role='footer' data-position='fixed'>\r\n");
      out.write("\t\t\t\t<h4 id='footerText'>Created by Szabolcs Kovacs <br> email: skovacs33@gmail.com</h4>\r\n");
      out.write("\t\t\t</div><!-- /footer -->\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
